### ISSUE TITLE
Sectioning the TOC

### ISSUE THREAD

**Issue by dgruntz** [scalapuzzlers/scalapuzzlers.github.com#29]
as soon as we have collected the first 100 puzzlers, we should think about a sectioning of the table of contents. Have not yet an idea how this sould be done, only wanted to add that as a reminder (as it needs to be prepared in the templates and in the sources of the site).

Dominik

**Comment by demobox** [comment]
In the book, we tried to categorize the puzzlers according to which part(s) of the language they touched. Something similar could be done here, but it often turned out to be a one-to-many mapping, so we'd probably need something other than straightforward sections.

Parking for now - thanks for the suggestion, Dominik!
